apache/incubator-kie-kogito-serverless-operator

Makefile

Clean task

---

PROJECT

Signed-off-by: Davide Salerno <dsalerno@redhat.com>
**Checklist**

[KOGITO-7839] Align apiGroup to sw.kogito.kie.org

---

.github/workflows/test-go.yml
README.md
builder/builder.go
config/crd/bases/sw.kogito.kie.org_kogitoserverlessbuilds.yaml
config/manager/kogito_builder_dockerfile.yaml
config/manager/kustomization.yaml
constants/const.go
controllers/kogitoserverlessbuild_controller.go
controllers/kogitoserverlessworkflow_controller.go
operator.yaml
utils/workflow.go

Signed-off-by: Davide Salerno <dsalerno@redhat.com>
See: [KOGITO-7981](https://issues.redhat.com/browse/KOGITO-7981)
**Checklist**

[KOGITO-7981] Provide a Build CRD for the kaniko Builder (refactor)

---

CONTRIBUTING.md
README.md

See: https://issues.redhat.com/browse/KOGITO-8164
Issue to move information about dev/test into a CONTRIBUTING.md file
Signed-off-by: desmax74 <mdessi@redhat.com>
**Checklist**

[Kogito-8164] Kogito Serverless Workflow Operator Documentation

---

.github/workflows/test-go.yml
.gitignore
api/v08/kogitoserverlessbuild_types.go
builder/buildable.go
builder/builder.go
controllers/kogitoserverlessbuild_controller.go
go.mod
go.sum
utils/workflow.go

Signed-off-by: spolti <fspolti@redhat.com>
**Checklist**

update container-build dependencies

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

See:https://issues.redhat.com/browse/KOGITO-8179
Signed-off-by: desmax74 <mdessi@redhat.com>
**Checklist**

[KOGITO-8179]-Fix Operator imports with Container-builder

---

CONTRIBUTING.md
README.md
hack/local/greeting_example_deploy.sh

Correct README

---

.github/workflows/e2e.yml
Makefile
bundle/manifests/kogito-serverless-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
operator.yaml
test/e2e/workflow_test.go
test/utils/utils.go

https://issues.redhat.com/browse/KOGITO-8177

KOGITO-8177 Setup e2e GHA

---

.ci/jenkins/dsl/jobs.groovy

KOGITO-8062 DSL: Refactor environments

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-backporting.yml

following: https://github.com/kiegroup/kogito-pipelines/pull/743

Automated pull request backporting workflow

---

.github/workflows/e2e.yml

See [v0.0.10](https://github.com/medyagh/setup-minikube/tree/v0.0.10)

GHA: Update `setup-minikube` version

---

.ci/jenkins/Jenkinsfile.setup-branch

https://issues.redhat.com/browse/KOGITO-8393

KOGITO-8393 Clean release notes on branching

---

builder/builder.go
go.mod
go.sum

WIP Merge after https://github.com/kiegroup/container-builder/pull/18
See: https://issues.redhat.com/browse/KOGITO-8520
Signed-off-by: max <mdessi@redhat.com>
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally …

[Kogito-8520] Separate plain builder API and Builder-k8s API

---

.ci/jenkins/Jenkinsfile.deploy

**Checklist**
<details>
<summary>
</summary>
Once the …

Correct deploy pipeline

---

hack/bump-version.sh

**Checklist**
<details>
<summary>
</summary>
Once the …

Correct bump-version script (#74)

---

.ci/jenkins/Jenkinsfile.setup-branch

**Checklist**
<details>
<summary>
</summary>
Once the …

Correct Setup Branch job

---

README.md
api/metadata/annotations.go
config/samples/sw.kogito_v1alpha08_kogitoserverlessworkflow_devmodeWithConfigMapAndExternalResource.yaml
config/samples/sw.kogito_v1alpha08_kogitoserverlessworkflow_devmodeWithExternalResource.yaml
controllers/profiles/reconciler_dev.go
controllers/profiles/reconciler_dev_test.go
test/yaml.go
utils/kubernetes/annotations.go
utils/kubernetes/volumes.go

See: https://issues.redhat.com/browse/KOGITO-8517
**Checklist**
<details>
<summary>
</summary> …

[KOGITO-8517] - Support external resources configuration for WorkflowCR in devmode

---

Dockerfile
README.md
RELEASE_NOTES.md
api/v1alpha08/kogitoserverlessplatform_types.go
bundle/manifests/sw.kogito.kie.org_kogitoserverlessplatforms.yaml
config/crd/bases/sw.kogito.kie.org_kogitoserverlessplatforms.yaml
config/samples/sw.kogito_v1alpha08_kogitoserverlessplatformWithBaseImage.yaml
config/samples/sw.kogito_v1alpha08_kogitoserverlessplatformWithDevBaseImage.yaml
controllers/profiles/object_creators.go
controllers/profiles/reconciler_dev.go
controllers/profiles/reconciler_dev_test.go
operator.yaml
platform/kaniko_cache.go
test/yaml.go
utils/kubernetes/security.go
version/version.go

See: https://issues.redhat.com/browse/KOGITO-8675
**Checklist**
<details>
<summary>
</summary> …

[KOGITO-8675] Make Workflow Dev Profile builder image configurable via Platform

---

.ci/jenkins/Jenkinsfile.setup-branch
.ci/jenkins/dsl/jobs.groovy

This is the nightly responsibility
https://issues.redhat.com/browse/KOGITO-8981
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/932
- https://github.com/kiegroup/kogito-runtimes/pull/2926
- https://github.com/kiegroup/kogito-apps/pull/1693
- https://github.com/kiegroup/kogito-examples/pull/1633
- https://github.com/kiegroup/kogito-images/pull/1487
- https://github.com/kiegroup/kogito-operator/pull/1453
- https://github.com/kiegroup/kogito-serverless-operator/pull/89
- https://github.com/kiegroup/kogito-docs/pull/327

KOGITO-8981 Setup branch should not deploy

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/scripts/minikube.groovy
.github/workflows/e2e.yml
hack/kube-utils.sh

**Checklist**
<details>
<summary>
</summary>
Once the …

Update k8s/minikube versions

---

utils/kubernetes/security.go

**Checklist**
<details>
<summary>
</summary>
Once the …

[KOGITO-8675] - Fixing wrong security context RunAsNonRoot value

---

go.mod
go.sum
test/e2e/workflow_test.go

See: https://issues.redhat.com/browse/KOGITO-8799
**Checklist**
<details>
<summary>
</summary> …

[KOGITO-8799] Add Kubernetes security profile to Kaniko and builder pods

---

.github/workflows/check-container-builder.yml
controllers/profiles/reconciler_dev.go
controllers/profiles/reconciler_dev_test.go

https://issues.redhat.com/browse/KOGITO-9138
Related:
- https://github.com/kiegroup/kogito-images/pull/1531
- https://github.com/kiegroup/kogito-serverless-operator/pull/116

KOGITO-9138 Use new swf devmode image

---

bundle/manifests/kogito-serverless-operator-builder-config_v1_configmap.yaml
config/manager/kogito_builder_dockerfile.yaml
config/samples/sw.kogito_v1alpha08_kogitoserverlessplatform_withCache.yaml
config/samples/sw.kogito_v1alpha08_kogitoserverlessplatform_withCacheAndCustomization.yaml
config/samples/sw.kogito_v1alpha08_kogitoserverlessplatform_withCache_minikube.yaml
controllers/profiles/reconciler_dev.go
controllers/profiles/reconciler_dev_test.go
operator.yaml
test/builder/Dockerfile
utils/workflow.go
version/version.go

**Checklist**
<details>
<summary>
</summary>
Once the …

[1.38.x] Prepare for release

---

.ci/jenkins/Jenkinsfile.deploy

**Checklist**
<details>
<summary>
</summary>
Once the …

CI: Fix Jenkinsfile.deploy

---

.github/workflows/check-container-builder.yml
bundle/manifests/kogito-serverless-operator-builder-config_v1_configmap.yaml
config/manager/kogito_builder_dockerfile.yaml
container-builder/examples/api/PlatformBuild_usingKanikowithCache.yaml
controllers/profiles/reconciler_prod.go
controllers/profiles/reconciler_prod_test.go
hack/addheaders.sh
operator.yaml
test/samples/sw.kogito_v1alpha08_kogitoserverlessworkflow.yaml
utils/kubernetes/annotations.go

See: https://issues.redhat.com/browse/KOGITO-8644
**Checklist**
<details>
<summary>
</summary> …

[KOGITO-8644] - Review "applied" status attribute

---

osl-image-prod.yaml

This PR is just to update Cachito to the latest commit on the main branch. The reason is that I want to test building the Operator image via CPaaS and the commit that created the `osl-image-prod.yaml` is not included in the current commit that is in `ref`.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to …

update ref in osl-image-prod.yaml to the latest commit from main branch

---

.ci/jenkins/Jenkinsfile.deploy

**Checklist**
<details>
<summary>
</summary>
Once the …

CI: Fix Jenkinsfile deploy prepare tests

---

.ci/jenkins/Jenkinsfile.deploy

Tests before update version ...
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one …

[1.39.x] Fix specific to release 1.39.x

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/Jenkinsfile.setup-branch
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/scripts/container.groovy
.ci/jenkins/scripts/helper.groovy

https://issues.redhat.com/browse/KOGITO-9259

KOGITO-9259 CI: RHEL8 fixes

---

controllers/platform/defaults.go
controllers/platform/platformutils.go

See https://issues.redhat.com/browse/KOGITO-9255
**Checklist**
<details>
<summary>
</summary> …

[KOGITO-9255]Cannot create Workflow on Openshift if  is set

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.e2e.cluster
.ci/jenkins/dsl/jobs.groovy
bundle/manifests/kogito-serverless-operator.clusterserviceversion.yaml
config/samples/sw.kogito_v1alpha08_kogitoserverlessworkflow.yaml
config/samples/sw.kogito_v1alpha08_kogitoserverlessworkflow_devmodeWithConfigMapAndExternalResource.yaml
test/e2e/workflow_test.go
test/testdata/sw.kogito_v1alpha08_kogitoserverlessplatform_openshift.yaml
test/testdata/sw.kogito_v1alpha08_kogitoserverlessplatform_withCache_minikube.yaml
test/testdata/sw.kogito_v1alpha08_kogitoserverlessworkflow_devmode.yaml
test/yaml.go

https://issues.redhat.com/browse/KOGITO-9011
Setup nightlies and PR checks to run on Openshift

KOGITO-9011 Nightly testing on Openshift

---

.ci/jenkins/Jenkinsfile

https://issues.redhat.com/browse/KOGITO-9322

[KOGITO-9322] Setup OCP PR checks

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/scripts/helper.groovy
Makefile
image.yaml

https://issues.redhat.com/browse/KOGITO-9291

KOGITO-9291 Build multiplatform

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/PULL_REQUEST_TEMPLATE.md
README.md
bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
config/manifests/bases/sonataflow-operator.clusterserviceversion.yaml
test/e2e/e2e_suite_test.go
test/e2e/workflow_test.go

Quick PR to rename a few files to the right wording.

Fix SonataFlow project naming

---

bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
controllers/builder/openshiftbuilder_test.go
controllers/workflowdef/image.go

We need to handle version change correctly in tests

[1.40.x] Correct testing due to version change

---

.ci/jenkins/Jenkinsfile
.ci/jenkins/Jenkinsfile.e2e.cluster

platform CR paths have changed

[1.40.x] Fix e2e tests

---

controllers/builder/openshiftbuilder_test.go
controllers/workflowdef/image.go

**Checklist**
<details>
<summary>
</summary>
Once the …

Remove default image as public constants

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/scripts/helper.groovy
hack/bump-version.sh
hack/env.sh

https://issues.redhat.com/browse/KOGITO-9492
- `image.yaml` was not correctly updated
- bundle csv use Major.minor instead of full version
- CI will publish the Major.minor image
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, …

KOGITO-9492 Update bump-version script

---

.ci/jenkins/Jenkinsfile.deploy

**Checklist**
<details>
<summary>
</summary>
Once the …

[1.41.x] Allow to override the Container registry URL

---

.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/scripts/helper.groovy

Improve tagging and module dependencies update
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of …

KOGITO-9471 CI: Correct promote pipeline

---

bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
config/manifests/bases/sonataflow-operator.clusterserviceversion.yaml
hack/bump-version.sh
hack/env.sh

**Checklist**
<details>
<summary>
</summary>
Once the …

Fix csv file on bump version

---

.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/scripts/helper.groovy
Makefile
bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
hack/bump-version.sh
hack/env.sh
operator.yaml
workflowproj/workflowproj_test.go

In order to perform a new bug fix release correctly
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a …

Pipelines cherry-picks

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/scripts/helper.groovy

https://issues.redhat.com/browse/KOGITO-9671
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/1022
- https://github.com/kiegroup/drools/pull/5434
- https://github.com/kiegroup/kogito-runtimes/pull/3159
- https://github.com/kiegroup/kogito-apps/pull/1818
- https://github.com/kiegroup/kogito-examples/pull/1756
- https://github.com/kiegroup/kogito-images/pull/1662
- https://github.com/kiegroup/kogito-operator/pull/1503
- https://github.com/kiegroup/kogito-serverless-operator/pull/213
- https://github.com/kiegroup/optaplanner/pull/2921

KOGITO-9671 CI: Remove bot account usage

---

Dockerfile
go.work.sum

**Checklist**
<details>
<summary>
</summary>
Once the …

[KOGITO-8276] Fixing Dockerfile to COPY the new log package

---

bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
controllers/const.go
docs/CONTRIBUTING.md
main.go
operator.yaml

See: https://issues.redhat.com/browse/KOGITO-8276
The operator doesn't print nothing
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about …

[KOGITO-8276] Fix setup log

---

.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/scripts/helper.groovy

https://issues.redhat.com/browse/KOGITO-9676
- https://github.com/kiegroup/kogito-pipelines/pull/1023
- https://github.com/kiegroup/kogito-runtimes/pull/3162
- https://github.com/kiegroup/kogito-apps/pull/1821
- https://github.com/kiegroup/kogito-examples/pull/1758
- https://github.com/kiegroup/kogito-images/pull/1665
- https://github.com/kiegroup/kogito-operator/pull/1509
- https://github.com/kiegroup/kogito-serverless-operator/pull/222

KOGITO-9676 CI: Promote call setup-branch job

---

.ci/jenkins/Jenkinsfile.e2e.cluster

**Checklist**
<details>
<summary>
</summary>
Once the …

[1.43.x] Fix e2e for releases

---

.ci/jenkins/Jenkinsfile.promote

**Checklist**
<details>
<summary>
</summary>
Once the …

[1.43.x] Fix promote pipeline

---

bundle/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
container-builder/builder/kubernetes/testdata/Dockerfile
container-builder/examples/dockerfiles/SonataFlow.dockerfile
controllers/platform/platformutils_test.go
go.mod
go.sum
go.work.sum
operator.yaml
test/builder/Dockerfile

**Checklist**
<details>
<summary>
</summary>
Once the …

[1.43.x] Correction versions

---

.ci/jenkins/Jenkinsfile
.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.e2e.cluster
.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/Jenkinsfile.setup-branch
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/scripts/minikube.groovy

- https://github.com/kiegroup/kogito-runtimes/pull/3206
- https://github.com/kiegroup/kogito-apps/pull/1876
- https://github.com/kiegroup/kogito-examples/pull/1790
- https://github.com/kiegroup/kogito-images/pull/1697
- https://github.com/kiegroup/kogito-operator/pull/1527
- https://github.com/kiegroup/kogito-serverless-operator/pull/249
- https://github.com/kiegroup/drools/pull/5518
- https://github.com/asf-transfer/optaplanner/pull/2967

[apache_migration] Update pipelines

---

workflowproj/workflowproj_test.go

Quick PR to fix flaky tests in the `workflowproj` module.

Fix workflowproj flaky tests by sorting arrays

---

bundle.osl/manifests/logic-operator-rhel8.clusterserviceversion.yaml
bundle.osl/manifests/sonataflow.org_sonataflows.yaml
docs/PRODUCTIZATION.md

… 
**Checklist**
<details>
<summary>
</summary>
Once the …

[KOGITO-9103] [KSW-Operator] add missing podTemplate to bundle.osl and update readme

---

bddframework/pkg/config/config.go
bddframework/pkg/framework/maven.go
hack/run-tests.sh

Changes references to JBoss Nexus to Apache Nexus.

[kie-issues#628] Change JBoss Nexus to Apache Nexus.

---

workflowproj/README.md

Tiny update to function name in code snippet from workflowprog/README.md
Consistency.

Update workflowproj README.md

---

api/go.mod
api/go.sum
go.mod
go.sum
go.work
go.work.sum
testbdd/go.mod
testbdd/go.sum
workflowproj/go.mod
workflowproj/go.sum

In this PR, we upgrade the Go SDK to v2.2.5. More information here: https://github.com/serverlessworkflow/sdk-go/releases/tag/v2.2.5
Closes https://github.com/apache/incubator-kie-issues/issues/660
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) …

[issues-660] Upgrade CNCF SW Go SDK to 2.2.5 version

---

.github/workflows/check-container-builder.yml
.github/workflows/checks.yml
.github/workflows/e2e.yml

Fix #295 
<details>
<summary>
</summary>
Once the original pull request is successfully …

Fix #295 - Run apt-get update and skip recommends

---

.ci/jenkins/Jenkinsfile.deploy

Tries to close #300 
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to …

:door: Use random port for local registry

---

.ci/jenkins/Jenkinsfile.deploy

We have a typo in the pipeline where we redeclare a global var. 
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific …

Fix #300 - Remove declaration of local variable

---

bundle/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
config/manager/osl/sonataflow_builder_dockerfile.yaml
config/manager/sonataflow_builder_dockerfile.yaml
operator.yaml
test/builder/Dockerfile

See: https://issues.redhat.com/browse/KOGITO-9729
Also see: https://github.com/apache/incubator-kie-kogito-images/pull/1711
Aligning our default dockerfiles to use the image's user when copying files over the build context.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a …

[KOGITO-9729] Fix permissions in default builder Dockerfile

---

bundle.osl/manifests/logic-operator-rhel8-builder-config_v1_configmap.yaml
bundle/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
config/manager/osl/sonataflow_builder_dockerfile.yaml
config/manager/sonataflow_builder_dockerfile.yaml
container-builder/builder/kubernetes/testdata/Dockerfile
container-builder/examples/dockerfiles/SonataFlow.dockerfile
operator.yaml
test/builder/Dockerfile

**Checklist**
<details>
<summary>
</summary>
Once the …

kogito-serverless-operator-343: Move workflows execution JDK to java17

---

Makefile
test/e2e/workflow_test.go

Issue:  https://github.com/apache/incubator-kie-issues/issues/755
We have experienced a number of test timeouts in the nightly pipeline running on Apache Jenkins.
This PR increases the timeouts for E2E tests that runs on Minikube.

kie-issues#755 - Increase E2E tests timeouts

---

.github/workflows/check-container-builder.yml
.github/workflows/checks.yml
container-builder/builder/kaniko_integration_test_suite.go
container-builder/cleaner/docker_integration_test.go
container-builder/cleaner/docker_integration_test_suite.go
container-builder/cleaner/registry_docker_integration_test.go
container-builder/common/registry.go
container-builder/common/registry_docker.go

Fix #364 
**Checklist**
<details>
<summary>
</summary> …

Fix #364 pipelines using an old Ubuntu version

---

.github/workflows/e2e.yml
bundle.osl/manifests/logic-operator-rhel8-controller-manager-metrics-service_v1_service.yaml
bundle.osl/manifests/logic-operator-rhel8.clusterserviceversion.yaml
bundle/manifests/sonataflow-operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/manager/osl/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_service.yaml
operator.yaml
testbdd/steps/operator.go

Fix #366 - Add custom label to manifests to avoid clashing with installed operators in a cluster

---

api/v1alpha08/sonataflowclusterplatform_types.go
api/v1alpha08/sonataflowplatform_types.go
bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
bundle/manifests/sonataflow.org_sonataflowclusterplatforms.yaml
config/crd/bases/sonataflow.org_sonataflowclusterplatforms.yaml
config/manifests/bases/sonataflow-operator.clusterserviceversion.yaml
operator.yaml

add required items to CSV
run this to validate
```bash
$ operator-sdk scorecard bundle
```
fixes https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/387
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which …

[387] fix csv scorecard issues

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/dsl/jobs.groovy

Additional fix needed to setup the jobs 
See here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/nightly/job/kogito-serverless-operator.e2e.minikube/20/

#376: kso-issue-376: Configure the dsl to setup e2e with kind

---

.ci/jenkins/Jenkinsfile.weekly.deploy

This PR fixes the weekly job image push to quay.io

NO-ISSUE: Fix weekly job image push to quay.io

---

.ci/jenkins/Jenkinsfile
.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.e2e.cluster
.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/Jenkinsfile.setup-branch
.ci/jenkins/Jenkinsfile.weekly.deploy

part of https://github.com/apache/incubator-kie-issues/issues/777

kie-issues#777: Allow restricting jenkins agent labels for pipelines

---

controllers/platform/services/properties.go
controllers/profiles/dev/object_creators_dev.go
controllers/profiles/dev/profile_dev.go
controllers/profiles/prod/profile_prod.go
controllers/profiles/profile.go
controllers/profiles/profile_test.go
workflowproj/operator.go
workflowproj/workflowproj.go

Fixes #402 - `workflowproj` can't have dependencies on the `kogito-serverless-workflow` module, otherwise it will bring too many files and dependencies to client code.
Avoid circular and dependency bloat.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the …

Issue #402 - Move profiles check to workflowproj module

---

.ci/jenkins/Jenkinsfile.weekly.deploy

Follow up on: https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/394

NO-ISSUE: Configure weekly job to setup e2e tests with Kind

---

bddframework/go.mod
bddframework/go.sum
go.mod
go.sum
go.work.sum
testbdd/go.mod
testbdd/go.sum

So we can close:
- #419 
- #418

NO-ISSUE - [dependabot] Upgrade CloudEvents SDK to 2.15.2

---

api/go.mod
api/go.sum
bddframework/go.mod
bddframework/go.sum
container-builder/go.mod
container-builder/go.sum
go.mod
go.sum
go.work.sum
testbdd/go.mod
testbdd/go.sum
workflowproj/go.mod
workflowproj/go.sum

Fix #430 
Upgrade protobuf to fix vulnerabilities.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a …

ISSUE-430: Upgrade protobuf from 1.31.0 to 1.33.0

---

images/requirements.txt

Attempt to fix Python env when running GHA or PR checks.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change …

NO ISSUE: Fix Python dependencies in e2e

---

bddframework/go.mod
bddframework/go.sum
container-builder/go.mod
container-builder/go.sum
go.mod
go.sum
go.work.sum
testbdd/go.mod
testbdd/go.sum

Manually bumping versions to reflect the code changes.
See: https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/518/
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still …

NO-ISSUE: Fix CVE upgrading google.golang.org/grpc from 1.64.0 to 1.64.1

---

hack/addheaders.sh
images/bundle.yaml
images/manager.yaml
images/modules/org.apache.kie.sonataflow.bundle/module.yaml
images/modules/org.apache.kie.sonataflow.goModDownload/module.yaml
images/modules/org.apache.kie.sonataflow.operatorBuilder/module.yaml
images/tools/sonataflow-db-migrator/pom.xml
images/tools/sonataflow-db-migrator/src/test/java/org/kie/kogito/postgresql/migrator/DBConnectionCheckerTest.java
images/tools/sonataflow-db-migrator/src/test/java/org/kie/kogito/postgresql/migrator/DBMigratorTest.java
images/tools/sonataflow-db-migrator/src/test/java/org/kie/kogito/postgresql/migrator/MigrationServiceTest.java

**Checklist**
<details>
<summary>
</summary>
Once the …

NO-ISSUE: add images folder to header check

---

controllers/platform/platformutils.go
controllers/platform/platformutils_test.go

Closes: #533 
**Checklist**
<details>
<summary>
</summary> …

kie-kogito-serverless-operator-533: Builder image is not used according to the configuration semantic
