Makefile
config/manager/kustomization.yaml
operator.yaml

Signed-off-by: Davide Salerno <dsalerno@redhat.com>

Changes in order to be able to deploy in k8s/ocp the operator

---

api/v08/kogitoserverlessworkflow_types.go
config/crd/bases/sw.kogito.kie.org_kogitoserverlessworkflows.yaml

**[KOGITO-7838]** - Alignment of the API for the Workflow object in the PoC with the Design document
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
Alignment of the API for the Workflow object in the PoC with the Design document
https://docs.google.com/document/d/1dvNlQ5tea2ixqOgucd-sLDPczrgwnYBNjbFyLkTvPUI/edit#heading=h.bmrte0aczgql
**Checklist**

[KOGITO-7838] - Alignment of the API for the Workflow object

---

api/v08/kogitoserverlessworkflow_types.go

Signed-off-by: desmax74 <mdessi@redhat.com>
**Checklist**

[Kogito-8082]Relaxing constraint on state fields branches duration onEvents

---

.github/workflows/test-go.yml

update pr job to re-trigger when PR is updated

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.setup-branch
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/scripts/container.groovy
.ci/jenkins/scripts/helper.groovy
.ci/jenkins/scripts/openshift.groovy
.ci/jenkins/scripts/properties.groovy
.github/workflows/jenkins-tests-PR.yml
Makefile
bundle.Dockerfile
bundle/manifests/kogito-serverless-operator-builder-config_v1_configmap.yaml
bundle/manifests/kogito-serverless-operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/kogito-serverless-operator-manager-config_v1_configmap.yaml
bundle/manifests/kogito-serverless-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/kogito-serverless-operator.clusterserviceversion.yaml
bundle/manifests/sw.kogito.kie.org_kogitoserverlessbuilds.yaml
bundle/manifests/sw.kogito.kie.org_kogitoserverlessworkflows.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml
config/samples/kustomization.yaml
hack/bump-version.sh
hack/ci/install-operator-sdk.sh
hack/env.sh

https://issues.redhat.com/browse/KOGITO-8175
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/664
- https://github.com/kiegroup/kogito-serverless-operator/pull/34

KOGITO-8175 Setup Nightly pipeline

---

Makefile
bundle/manifests/kogito-serverless-operator-builder-config_v1_configmap.yaml
bundle/manifests/kogito-serverless-operator.clusterserviceversion.yaml
bundle/manifests/sw.kogito.kie.org_kogitoserverlessbuilds.yaml
bundle/manifests/sw.kogito.kie.org_kogitoserverlessworkflows.yaml
config/manager/kustomization.yaml
config/samples/kustomization.yaml

To be in sync with the rest of the projects
Issue raised in https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/setup-branch/job/kogito-serverless-operator/1/console

Update version to 2.0.0-snapshot and harmonize bundle

---

CONTRIBUTING.md
Makefile
go.mod
go.sum

See: https://issues.redhat.com/browse/KOGITO-8194
Signed-off-by: desmax74 <mdessi@redhat.com>
**Checklist**

[KOGITO-8194] Upgrade Kogito-serverless-operator to operator-sdk 1.25

---

.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/scripts/container.groovy

https://issues.redhat.com/browse/KOGITO-8273

KOGITO-8273 Fallback to Docker build in Jenkins

---

.ci/jenkins/Jenkinsfile.deploy
Makefile
bundle/manifests/kogito-serverless-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
hack/bump-version.sh
operator.yaml

https://issues.redhat.com/browse/KOGITO-8535
On branches nightly, the version is set with `-snapshot` version so we just push the nightly image as it is built.
The default image name on branch will be nightly.
Once a release is done, the imageTagBase will be changed to prod one.
And we push all together.

KOGITO-8535 Deploy pipelines: Push built image

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.setup-branch
hack/env.sh

Correction on https://github.com/kiegroup/kogito-serverless-operator/pull/59

Correct deploy pipeline

---

hack/bump-version.sh

**Checklist**
<details>
<summary>
</summary>
Once the …

[1.34.x] Correct bump version script

---

api/v1alpha08/zz_generated.deepcopy.go
controllers/profiles/object_creators.go
controllers/profiles/object_creators_test.go
controllers/profiles/reconciler_dev.go
controllers/profiles/reconciler_dev_test.go
utils/kubernetes/env.go
utils/kubernetes/env_test.go

Adding the health checks to the default deployment. It requires a change in the builder image to include the health check addon. We might also have to disable the Knative health check in dev profile.
Depends on:
- https://github.com/kiegroup/kogito-images/pull/1444
See: https://issues.redhat.com/browse/KOGITO-8642
**Checklist**
<details>
<summary>
</summary>
> …

[KOGITO-8642] - Introduce health checks to the default Deployment

---

controllers/profiles/reconciler_dev.go

See: [KOGITO-8748](https://issues.redhat.com/browse/KOGITO-8748)
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific …

[KOGITO-8748] Recover from failure algorithm is ignoring RequeueAfter

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/scripts/minikube.groovy
.github/workflows/e2e.yml
hack/kube-utils.sh
operator.yaml

* Update k8s/minikube versions
* Update .ci/jenkins/scripts/minikube.groovy
* update in scripts
* wait for pod method
* updat
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained …

[1.37.x] Update k8s/minikube versions (#92)

---

.ci/jenkins/Jenkinsfile.deploy
hack/bump-version.sh

**Checklist**
<details>
<summary>
</summary>
Once the …

Jenkins deploy job: e2e failure results in unstable

---

.github/workflows/check-container-builder.yml

We don't want that the container-builder action will be executed when there isn't a change on that package.
If no change will be performed on the container-builder it will be better not to execute the GHA related to this module.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a …

[CI] Execute container-builder ci action only when needed

---

controllers/profiles/object_creators.go
controllers/profiles/object_creators_dev.go
controllers/profiles/reconciler_dev_test.go

See:https://issues.redhat.com/browse/KOGITO-9207
**Checklist**
<details>
<summary>
</summary> …

[Kogito-9207] [Operator] Make QUARKUS_KOGITO_DEVSERVICES_ENABLED and QUARKUS_DEVSERVICES_ENABLED properties immutable in devmode

---

.github/workflows/jenkins-tests-PR.yml
.github/workflows/pr-backporting.yml

Related PR:
- https://github.com/kiegroup/kie-ci/pull/1495

Updating references to the new kie-ci actions folder.

---

controllers/profiles/object_creators_dev.go
controllers/profiles/reconciler_dev.go
controllers/profiles/reconciler_dev_test.go

Small change to enhance devmode experience: https://issues.redhat.com/browse/KOGITO-9262
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is …

[KOGITO-9262] extend devmode probes threshold

---

hack/get-images-sha.sh

This script allows to fetch the sha256 of any image built in Brew. Currently it is fetching just the Operator as the sha256 of the Operator is required when building the Bundle.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, …

add hack/get-images-sha.sh script

---

workflowproj/workflowproj.go

In this PR we removed the owner references to the child objects because we can only perform this operating having the owner object ID. Since the workflow is not created yet, we can't possibly know. During the first reconciliation, thou, the operator will add this reference to the properties `configMap`, which is enough. The other generated CMs shouldn't have this reference since we won't reconcile or own them.
See: https://issues.redhat.com/browse/KOGITO-9290
**Checklist**
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is …

[KOGITO-9290] Removing Owner references from generated objects

---

workflowproj/go.mod
workflowproj/go.sum

With this fix, everyone will be able to use the `workflowproj` go module outside the Kogito Servereless Workflow Operator
We cannot use the `workflowproj` go module outside the Kogito Servereless Workflow Operator, due to the fact that we are using a `replace` directive into the `go.mod` and at the same time the `api` go module is without version.
**Checklist**
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the …

Fixing workflowproj module importing latest Operator apis

---

workflowproj/go.mod
workflowproj/go.sum

See:https://issues.redhat.com/browse/KOGITO-9348
**Checklist**
<details>
<summary>
</summary> …

[KOGITO-9348][OPERATOR-KSW] API version not updated in workflowproj module

---

bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
controllers/builder/containerbuilder.go
controllers/builder/openshiftbuilder.go
controllers/platform/platformutils.go
controllers/platform/platformutils_test.go
test/yaml.go

I added a the `GetCustomizedDockerfile`  func that will let us replace the base builder image used into the Dockerfile the Operator has got into the common builder ConfigMap with the `platform.spec.platform.baseImage` (only if present).
See [KOGITO-9244](https://issues.redhat.com/browse/KOGITO-9244)
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: …

[KOGITO-9244]  Platform.spec.platform.baseImage does not update the Dockerfile base image

---

Makefile
bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
hack/bump-version.sh
operator.yaml

https://issues.redhat.com/browse/KOGITO-9560
Result for a release branch: https://github.com/kiegroup/kogito-serverless-operator/commit/e3723e901688251b9bc345f331f77f5183d2cf1f
Result for the main branch can be found in this PR

KOGITO-9560 Use `latest` version in CSV

---

.gitignore
controllers/profiles/reconciler_dev.go
utils/kubernetes/deployment.go

We used to handle deployment progress wrongly, hence spamming unneeded deployment rollouts. After this change, our handlers will wait until a failure before doing a rollout.
See: https://issues.redhat.com/browse/KOGITO-9653
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually …

[KOGITO-9653] - Fix how to handle WaitingForDeployment condition to avoid pod duplication

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/scripts/helper.groovy

JIRA: [5386](https://issues.redhat.com/browse/KOGITO-5386)
related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/1024
- https://github.com/kiegroup/kogito-runtimes/pull/3161
- https://github.com/kiegroup/kogito-apps/pull/1820
- https://github.com/kiegroup/kogito-examples/pull/1757
- https://github.com/kiegroup/kogito-images/pull/1666
- https://github.com/kiegroup/kogito-operator/pull/1504
- https://github.com/kiegroup/kogito-serverless-operator/pull/218
The branch name during a release will be the same for all repositories deployed
**Checklist**
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more …

KOGITO-5386: added a new parameter for unique branch name

---

controllers/platform/warm.go
controllers/profiles/deployment.go
controllers/profiles/object_creators.go
controllers/profiles/reconciler_dev.go
controllers/profiles/reconciler_prod.go
controllers/profiles/reconciler_prod_test.go
controllers/sonataflowplatform_controller.go
utils/kubernetes/deployment.go
utils/kubernetes/deployment_failure.go
workflowproj/operator.go

In this PR we made a few changes to the deployment handler to be the same for both profiles (dev and prod).
Also, there was a small bug in the `SonataFlowPlatform` in the warm action that prevented it to mark as a status `true`.
Additionally, now it's easier to spot a bug when something happens to the deployment and it has not reached the minimum replicas available.
See JIRA https://issues.redhat.com/browse/KOGITO-8794
**Checklist**
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull …

[KOGITO-8794] - Making deployment handler profile independent

---

.github/workflows/jenkins-tests-PR.yml

**Checklist**
<details>
<summary>
</summary>
Once the …

Fix DSL check

---

container-builder/builder/kubernetes/kaniko.go

When using multi-stage builds, the /product_uuid path should be disabled. If not, the build fails in certain cases.
Error message:
```
[INFO] ------------------------------------------------------------------------
INFO[0123] Taking snapshot of full filesystem...
INFO[0128] Saving file home/kogito/serverless-workflow-project/target/quarkus-app/lib for later use
INFO[0128] Saving file home/kogito/serverless-workflow-project/target/quarkus-app/quarkus-run.jar for later use
INFO[0128] Saving file home/kogito/serverless-workflow-project/target/quarkus-app/app for later use
INFO[0128] Saving file home/kogito/serverless-workflow-project/target/quarkus-app/quarkus for later use
INFO[0128] Deleting filesystem...
error building image: deleting file system after stage 0: unlinkat //product_uuid: …
```

fix: issues with kaniko build

---

controllers/profiles/object_creators.go
controllers/profiles/object_creators_test.go
test/testdata/order-processing/04_v1_configmap_properties.yaml
test/testdata/order-processing/README.md

In this PR, we fixed a bug where the internal operator's properties parsing is trying to expand `${}`.
See https://issues.redhat.com/browse/KOGITO-9773
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still …

Fix property expansion problem

---

.ci/jenkins/Jenkinsfile
.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/Jenkinsfile.e2e.cluster
.ci/jenkins/Jenkinsfile.promote
.ci/jenkins/Jenkinsfile.setup-branch
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/dsl/test.sh
.ci/jenkins/scripts/minikube.groovy
.github/ISSUE_TEMPLATE/config.yml
.github/workflows/jenkins-tests-PR.yml

apache/incubator-kie-kogito-pipelines#1090
apache/incubator-kie-kogito-runtimes#3233
apache/incubator-kie-kogito-apps#1882
apache/incubator-kie-kogito-examples#1810
apache/incubator-kie-kogito-images#1703
apache/incubator-kie-kogito-operator#1530
apache/incubator-kie-kogito-serverless-operator#257
apache/incubator-kie-kogito-docs#504
apache/incubator-kie-docs#4529
apache/incubator-kie-drools#5531
apache/incubator-kie-optaplanner#2985
apache/incubator-kie-optaplanner-quickstarts#607
apache/incubator-kie-benchmarks#262

kie-issues#574 Initial ASF Jenkins CI Setup

---

.github/workflows/check-container-builder.yml
.github/workflows/checks.yml
.github/workflows/e2e.yml
hack/ci/install-minikube.sh

After Apache migration, we need to ensure that our actions follow the organization's policy.
I've removed the third-party actions and added a new script to download, cache, and set up minikube for e2e.
Fix #259 
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) …

Fix #259 - Update GHA to follow Apache policies

---

container-builder/builder/kubernetes/builder_kaniko_test.go
container-builder/builder/kubernetes/kaniko.go

- Fixes the parameters construction for the kaniko builder which produced the issue.
When testing the tuning of the sonataflow-operator-builder-config Docker file, it was detected that introduced ARGs where not processed well at the time of producing the kaniko --build-param's for the kaniko image build.
This change fixes these parameters processing.
https://issues.redhat.com/browse/KOGITO-9819
**Checklist**
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to …

KOGITO-9819: [Operator image builder] Persistence not working in the image produced by operator generated image

---

controllers/profiles/reconciler_dev.go
controllers/profiles/reconciler_dev_test.go
controllers/workflowdef/configmap.go

In this PR, we do a small change when mounting the main flow definition to the devmode deployment. Now, the path is fixed to always mount in the root path.
See: https://issues.redhat.com/browse/KOGITO-9776
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the …

[KOGITO-9776] Make the workflow definition mount point to root path in devmode

---

utils/openshift/route_test.go

**Checklist**
<details>
<summary>
</summary>
Once the …

KOGITO-9739: Create OpenShift routes with HTTPS for SonataFlows

---

controllers/profiles/common/app_properties.go
controllers/profiles/common/app_properties_test.go
controllers/profiles/common/mutate_visitors.go
controllers/profiles/common/object_creators.go
controllers/profiles/common/object_creators_test.go
controllers/profiles/dev/object_creators_dev.go
controllers/profiles/dev/states_dev.go
controllers/profiles/prod/deployment_handler.go

In this PR, we add the ability to bind the default Kubernetes Service DNS to the `kogito.service.url`. This way, we can ease the integration with Data Index and Jobs Service. These services can now make calls to the deployed workflows within the same namespace.
See https://issues.redhat.com/browse/KOGITO-9751
**Checklist**
<details>
<summary>
</summary>
> …

[KOGITO-9751] - :link: Bind kogito.service.url to the default CM application properties

---

api/v1alpha08/sonataflow_types.go
api/v1alpha08/zz_generated.deepcopy.go
bundle.osl/manifests/logic-operator-rhel8.clusterserviceversion.yaml
bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
config/manager/osl/kustomization.yaml
config/manifests/bases/sonataflow-operator.clusterserviceversion.yaml
config/manifests/osl/bases/logic-operator-rhel8.clusterserviceversion.yaml
controllers/profiles/common/object_creators.go
controllers/profiles/common/object_creators_test.go
controllers/profiles/prod/profile_prod_test.go
hack/local/run-e2e.sh
hack/local/run-operator.sh

In this PR, we fix the `podTemplate` struct to include json inline serializable annotations.
See https://issues.redhat.com/browse/KOGITO-9857
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still …

[KOGITO-9857] Fix podTemplate struct to json inline

---

controllers/profiles/common/app_properties.go
controllers/profiles/common/app_properties_test.go
go.work.sum

- Adds the missing protocol.
- Introduces the ability to have set of properties that the operator generates by default,
but the user has the chance to override with their own values if needed.
https://issues.redhat.com/browse/KOGITO-9856
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a …

KOGITO-9856: [Operator] Operator calculated kogito.service.url don't have protocol

---

controllers/profiles/dev/object_creators_dev.go
controllers/profiles/dev/profile_dev_test.go
controllers/profiles/dev/states_dev.go
test/testdata/sonataflow.org_v1alpha08_sonataflow-metainf.yaml
test/testdata/v1_configmap_greetings_staticfiles.yaml
test/yaml.go
utils/kubernetes/naming.go
utils/strings.go

In this PR, we safely generate volume naming for the dev profile resources to avoid problems with mount paths like `META-INF/resources`.
See https://issues.redhat.com/browse/KOGITO-9890
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another …

[KOGITO-9890] Generate safe volume naming based on DNS 1035

---

controllers/profiles/common/deployment.go
controllers/profiles/common/ensurer.go
controllers/profiles/common/mutate_visitors.go
controllers/profiles/common/object_creators.go
controllers/profiles/dev/profile_dev_test.go
controllers/profiles/dev/status_enricher_dev_test.go
controllers/profiles/prod/deployment_handler.go
controllers/profiles/prod/deployment_handler_test.go
controllers/profiles/prod/profile_prod_test.go
controllers/sonataflow_controller_test.go
controllers/sonataflowbuild_controller_test.go
controllers/sonataflowplatform_controller_test.go
test/kubernetes_cli.go
test/yaml.go
utils/kubernetes/naming_test.go

In this PR, we fixed a critical bug where the controller won't update the podTemplate accordingly, making the GitOps use case unavailable.
See https://issues.redhat.com/browse/KOGITO-9908
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another …

[KOGITO-9908] Fix reconciliation to always ensure prod objects

---

api/v1alpha08/sonataflow_types.go
controllers/builder/kogitoserverlessbuild_manager.go
controllers/platform/defaults.go
controllers/platform/initialize.go
controllers/platform/platform.go
controllers/platform/platformutils.go
controllers/profiles/prod/states_prod.go
test/e2e/workflow_test.go

In this PR, we stabilize the use case to switch between prod and dev profiles in the `SonataFlow` CR instances.
Also, we've added the possibility to make the controller create a new default platform if none is found.
See https://issues.redhat.com/browse/KOGITO-8524
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to …

[KOGITO-8524] Enable toggle dev/prod profiles

---

.ci/jenkins/Jenkinsfile.deploy
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/scripts/helper.groovy

In this PR, we remove OpenShift e2e tests for this moment (might include it later if we get the infra), and update the requirements to fit Apache Jenkins to build and push nightly builds.
Fix #300 
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) …

Fix #300 - :o: Initial OpenShift removal, unnecessary checkout

---

controllers/platform/services.go
controllers/profiles/common/app_properties.go
controllers/profiles/common/app_properties_test.go

Leverage the `AppPropertyHandler` for Data Index custom properties.
The operator should support custom application properties for Data Index, just as it does for workflow.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is …

[KOGITO-9924] use AppPropertyHandler for Data Index custom properties

---

controllers/discovery/discovery.go
controllers/discovery/discovery_test.go
controllers/discovery/kubernetes_catalog.go
controllers/discovery/kubernetes_constants.go
controllers/discovery/port_utils.go
controllers/discovery/port_utils_test.go
controllers/discovery/queries.go
controllers/discovery/queries_test.go
controllers/discovery/test_utils.go
controllers/discovery/uri_parser.go
controllers/discovery/uri_parser_test.go
controllers/discovery/uri_utils.go
controllers/discovery/uri_utils_test.go
controllers/profiles/common/app_properties.go
controllers/profiles/common/app_properties_test.go

- Add the discovery of kubernetes Deployment, StatefulSet, and Ingress objects to the service discovery API.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. …

kie-issues-308: Operator driven service discovery API Phase2

---

workflowproj/workflowproj.go
workflowproj/workflowproj_test.go

Fixes #317 
**Checklist**
<details>
<summary>
</summary> …

Fix #317 - Make namespace an optional parameter when generating manifests in workflowproj

---

api/condition_types.go
api/status_types.go
api/v1alpha08/sonataflow_types.go
api/v1alpha08/sonataflowbuild_types.go
controllers/builder/containerbuilder.go
controllers/platform/defaults.go
controllers/profiles/common/deployment.go
controllers/profiles/common/reconciler.go
controllers/profiles/dev/profile_dev.go
controllers/profiles/dev/profile_dev_test.go
controllers/profiles/dev/states_dev.go
controllers/profiles/factory/factory.go
controllers/profiles/prod/deployment_handler.go
controllers/profiles/prod/deployment_handler_test.go
controllers/profiles/prod/profile_prod.go
controllers/profiles/prod/profile_prod_test.go
controllers/profiles/prod/states_prod.go
controllers/profiles/prod/states_prod_nobuild.go
controllers/sonataflow_controller.go
controllers/sonataflow_controller_test.go
controllers/sonataflowbuild_controller.go
controllers/sonataflowbuild_controller_test.go
controllers/workflows/workflows.go
test/kubernetes_cli.go
test/mock_service.go
utils/kubernetes/annotations.go

See https://issues.redhat.com/browse/KOGITO-8792
In this PR:
- We add the ability to register events for build phase changes within the workflow object.
- Users can now rebuild a failed build (or for any other reasons they need) by setting the annotation `sonataflow.org/restartBuild: true` to a given build instance.
- There's a small refactoring where we remove the `PostReconcile` method from the `StateSupport` struct since it does not belong there. The tradeoff is to add the noop implementation to other states. We could infer the annotation in the reconciliation state loop by verifying if it implements the post-reconcile hook and then calls it or we could create a hook and only call if it's not null. However, I decided to go to this path that looks cleaner and makes the interface easier …

[KOGITO-8792] - Add events to build controllers and the ability to restart a build

---

controllers/platform/k8s.go
workflowproj/operator.go

Set a specific selector for each service installed by the platform.
Closes #340
Having the same selector will cause issues with the service routing to the incorrect pod and also for issues with scaling.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main …

Set selector and label specific to platform service

---

controllers/platform/services/services.go
controllers/profiles/common/constants/platform_services.go

**Checklist**
<details>
<summary>
</summary>
Once the …

kogito-serverless-operator-356: Temporary use of the nightly images

---

.github/workflows/e2e.yml
Makefile
hack/ci/create-kind-cluster-with-registry.sh

Migrating to Kind will allow us to retrieve a concise log report of the running containers in the cluster when an E2E test fails.
PR also adds 2 new steps in the e2e to export the cluster logs
@ricardozanini @masayag @wmedvede PTAL.

[KOGITO-10013] Migrate from Minikube to Kind for E2E tests and export logs

---

container-builder/cleaner/docker_integration_test.go
controllers/platform/k8s.go
controllers/profiles/common/mutate_visitors.go
controllers/profiles/common/object_creators.go
utils/kubernetes/image.go
utils/kubernetes/image_test.go

In this PR, we add the ability to pick the `PullPolicy` in the containers we deploy based on the image tag to follow Kubernetes/OpenShift conventions.
Fix #359 
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally …

Fix #359 - Change pullpolicy conditionally based on image tag

---

test/e2e/platform_test.go

Disable test `with both Job Service and Data Index and ephemeral persistence and the workflow in a production profile` due to changes in the workflow that now forces it to require a persistence connection to work.
@ricardozanini PTAL.

Disable platform e2e test due to workflow explicitly requiring persistence

---

hack/ci/create-kind-cluster-with-registry.sh

Removes a hardcoded IP that defined the directory inside `/etc/containerd` for the registry configuration. When the IPs mismatched it caused a failure to pull or push images from the insecure registry via kaniko builder with Kind.   The correct approach is to use the IP from the docker network configuration for the registry container for both the directory name and the configuration contained within.
@wmedvede @ricardozanini PTAL.

Fixes kind create cluster script that contained a hardcoded IP

---

controllers/builder/containerbuilder.go
controllers/workflowdef/image.go
test/e2e/platform_test.go

- Use "latest" image tag and namespaced images generation.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change …

kie-kogito-serverless-operator-379: Investigate why non-dev scenarios now requires JDBC configuration

---

bundle.osl/manifests/logic-operator-rhel8-builder-config_v1_configmap.yaml
bundle/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
config/manager/osl/sonataflow_builder_dockerfile.yaml
config/manager/sonataflow_builder_dockerfile.yaml
operator.yaml

… argument to the swf-builder
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one …

kie-kogito-serverless-operator-411: incorporate the MAVEN_ARGS_APPEND argument to the swf-builder

---

controllers/platform/k8s.go
controllers/platform/services/services.go
controllers/platform/services/services_test.go
test/testdata/platform/services/preview/postgreSQL/02-sonataflow_platform.yaml
utils/kubernetes/env.go
utils/kubernetes/env_test.go

**Checklist**
<details>
<summary>
</summary>
Once the …

kie-kogito-serverless-operator-445: Add custom configuration to the DI and JS for operator managed deployments

---

.ci/jenkins/Jenkinsfile.promote

Part of:
* apache/incubator-kie-issues#776
Other related PRs:
* apache/incubator-kie-kogito-pipelines#1194
* apache/incubator-kie-benchmarks#286
* apache/incubator-kie-docs#4536
* apache/incubator-kie-kogito-runtimes#3501
* apache/incubator-kie-kogito-apps#2047
* apache/incubator-kie-kogito-examples#1914
* apache/incubator-kie-kogito-docs#626
* apache/incubator-kie-drools#5927
* apache/incubator-kie-optaplanner#3083
* apache/incubator-kie-kogito-serverless-operator#462
Replacing old approach to merge PRs:  merge locally + push into remote
New behavior relies on gh cli directly to approve and merge PR.

kie-issues#776: automate PR merge into protected branches

---

controllers/platform/services/services.go
controllers/profiles/common/persistence/persistence_suite_test.go
controllers/profiles/common/persistence/postgresql.go
controllers/profiles/common/persistence/postgresql_test.go

Closes #476 
**Checklist**
<details>
<summary>
</summary> …

kie-kogito-serverless-operator-476: Supporting service don't inherit platform persistence when the current service persistence is empty

---

api/metadata/annotations.go
api/metadata/annotations_test.go

https://github.com/apache/incubator-kie-issues/issues/1302
added IsValidProfile() to ProfileType
Adding an IsValidProfile() to ProfileType in the serverless-operator would be very handy.

added isValidProfile to ProfileType

---

api/v1alpha08/sonataflow_types.go
api/v1alpha08/sonataflowbuild_types.go
api/v1alpha08/sonataflowclusterplatform_types.go
api/v1alpha08/sonataflowplatform_types.go
bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
config/manifests/bases/sonataflow-operator.clusterserviceversion.yaml

Quick one to fix the `displayName` of our objects.
The `displayName` is used in multiple platforms to refer to our CRDs.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release …

:suspect: Fix resources display name

---

workflowproj/workflowproj.go
workflowproj/workflowproj_test.go

Motivation:
Workflowproj generates a configmap per schema or subflow or specs in a
separate file for each one, however the name is not deterministic. In
one iteration you can get the specs in
01-configmap-FLOWNAME-resources.yaml and in the next iteration the same
content will go in 02-configmap-FLOWNAME-resources.yaml.
While the flow spec file will be updated accordingly and stay correct,
the behaviour generates lots of changes when tracking changes in git.
Modification:
This fix will make the generation behaviour deterministic by sorting the
resources iteration prior to generating them and also add the related
schemas|specs/subflows to the generated file name:
Result:
old schema configmap manifest:
0x-configmap-FLOWNAME-resources.yaml
new schema configmap manifest: …

Generate stable names for workflow resources

---

.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/scripts/container.groovy
.ci/jenkins/scripts/helper.groovy
.github/workflows/jenkins-tests-PR.yml
.github/workflows/pr-backporting.yml

Description of the change:
https://github.com/apache/incubator-kie-issues/issues/1214
Depends on: https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/466

kie-issues#1214: Replace explicit references to quay.io images across CI pipelines

---

.ci/jenkins/scripts/helper.groovy

This PR fixes the `getImageRegistryUserCredentialsId` and the `getImageRegistryTokenCredentialsId` helper methods used in the CI jobs by removing the `IMAGE_` prefix as they are defined in each job according to their types.

NO-ISSUE: Fix image registry credentials helper methods

---

controllers/clusterplatform/clusterplatform.go
controllers/clusterplatform/initialize.go
controllers/platform/defaults.go
controllers/platform/initialize.go
controllers/platform/k8s.go
controllers/platform/monitor.go
controllers/platform/platform.go
controllers/platform/platformutils.go
controllers/profiles/common/properties/platform_test.go
controllers/sonataflowclusterplatform_controller.go
controllers/sonataflowplatform_controller.go
test/kubernetes_cli.go

The default `SonataFlowPlatform` created by the operator when the user does not, was missing the default configuration.
Fix #486
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained …

Fix #486 - Set the controller config to the default platform

---

README.md

This change is simply removing the Productization notes section form the README.
The Productization notes section into the README is no more needed.
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a …

fix: delete from README the Productization notes section

---

.ci/jenkins/dsl/jobs.groovy
hack/bump-version.sh

Fixes image names on CI after the migration to dockerhub and also fixes the script to bump the project version.

NO-ISSUE: Fix image names in CI and the script to bump versions

---

workflowproj/operator_test.go

Signed-off-by: Roy Golan <rgolan@redhat.com>

Add tests for workflowproj/operator.go

---

controllers/platform/services/properties_services_test.go
controllers/platform/services/services.go
controllers/profiles/common/constants/platform_services.go

closes: #491 
**Checklist**
<details>
<summary>
</summary> …

kie-kogito-serverless-operator-491: Make the Operator configure the Jobs Service Leader liveness check

---

api/v1alpha08/sonataflow_persistence_types.go
bundle/manifests/sonataflow.org_sonataflowplatforms.yaml
bundle/manifests/sonataflow.org_sonataflows.yaml
config/crd/bases/sonataflow.org_sonataflowplatforms.yaml
config/crd/bases/sonataflow.org_sonataflows.yaml
controllers/sonataflowplatform_controller_test.go
operator.yaml
test/testdata/workflow/persistence/by_service/04-sonataflow_callbackstatetimeouts.sw.yaml
test/testdata/workflow/persistence/from_platform_overwritten_by_service/03-sonataflow_callbackstatetimeouts.sw.yaml

Fix for #524 : Make migrateDBOnStartUp optional to avoid deployment errors 
**Checklist**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move …

Make migrateDBOnStartUp property optional

---

config/manager/manager.yaml
internal/controller/discovery/discovery_openshift_test.go
internal/controller/discovery/openshift_catalog.go
internal/controller/platform/services/services.go
internal/controller/profiles/common/constants/workflows.go
internal/controller/profiles/common/properties/managed.go
internal/controller/profiles/common/properties/managed_test.go
operator.yaml

**Checklist**
<details>
<summary>
</summary>
Once the …

kie-kogito-serverless-operator-536: Adjust cors configuration for the dev profile deployments, and JS and DI deployments

---

internal/controller/sonataflow_controller.go
internal/controller/sonataflowplatform_controller.go

This PR makes knative optional for SonataFlow Operator deployment. Fixes #541 
**Checklist**

Fix #541 Knative should not be required to install and run the SonataFlow Operator to deploy workflows

---

test/e2e/helpers.go

Fix #554 
Use a loop to retry the trigger data validation. This is because after the trigger gets created, it takes some time for it's status to get ready.
Make E2E test more stable.
**Checklist**

[issue-554] Knative trigger validation in E2E test randomly fails

---

bundle/manifests/sonataflow-operator-controllers-config_v1_configmap.yaml
config/manager/controllers_cfg.yaml
internal/controller/cfg/controllers_cfg.go
internal/controller/cfg/controllers_cfg_test.go
internal/controller/cfg/testdata/controllers-cfg-test.yaml
internal/controller/platform/services/services.go
internal/controller/profiles/common/constants/platform_services.go
internal/controller/profiles/common/constants/workflows.go
internal/controller/profiles/common/properties/managed.go
internal/controller/profiles/common/properties/managed_test.go
operator.yaml

**Checklist**
<details>
<summary>
</summary>
Once the …

kie-kogito-serverless-operator-548: Make the operator configure the kogito events grouping by default in preview and gitops workflow deployments

---

internal/controller/platform/k8s.go
internal/controller/platform/services/services.go

Fix #559
**Checklist**
<details>
<summary>
</summary>
Once …

kie-kogito-serverless-operator-559: Add the ability to scale the Jobs Service to 0

---

internal/controller/platform/services/properties.go

Closes: #568 
**Checklist**
<details>
<summary>
</summary> …

kie-kogito-serverless-operator-568: Disable Workflows DI and JS availability health checks when Knative Eventing is configured

---

config/rbac/role.yaml
internal/controller/profiles/common/knative_eventing.go
internal/controller/profiles/preview/states_preview.go
internal/controller/sonataflow_controller.go
operator.yaml

Fix issue https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/562.
The reason why the ***00001-deployment*** pod gets restarted repeatedly is because after K_SINK injection, a new Knative revision has been created, and the workflow managed properties configmap has been updated to use the the K_SINK environment variable. As such the first deployment ****_00001 has become outdated and no longer aligned with the configmap and this causes the repeated pod restarting.
The fix is to clean up the outdated Knative revision(s) after the K_SINK injection is done (ie, sinkbinding is ready).
To prevent ***00001-deployment*** pod from getting restarted repeatedly.
**Checklist**
- [X ] Add or Modify a unit test for your …

[issue-562] Serverless workflow pod gets restarted repeatedly after native K_SINK injection
